"""Init

Revision ID: e0c616096051
Revises: 
Create Date: 2025-12-25 00:27:49.060457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c616096051'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('time_frame', sa.String(), nullable=False),
    sa.Column('requested_plot', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'PENDING', 'FAILED', name='status_enum'), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.Column('used_cache', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_requests_created_at'), 'forecast_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_forecast_requests_isin'), 'forecast_requests', ['isin'], unique=False)
    op.create_index(op.f('ix_forecast_requests_user_id'), 'forecast_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_requests_user_id'), table_name='forecast_requests')
    op.drop_index(op.f('ix_forecast_requests_isin'), table_name='forecast_requests')
    op.drop_index(op.f('ix_forecast_requests_created_at'), table_name='forecast_requests')
    op.drop_table('forecast_requests')
    # ### end Alembic commands ###
